### ISSUE TITLE
State of the project. (Transferring repo soon, please read)

### ISSUE THREAD

**Issue by eliasdaler** [SFML/imgui-sfml#233]
## **UPD (15.02.2023) - the repo has been transferred to SFML organization. I'm not completely gone and might participate in further development occasionally. I'm just not the main maintainer anymore. :)**

I'm thinking about archiving^W **transferring** this project and choosing a "true successor" fork to link in the README. 
Please leave your thoughts here or feel free to send me e-mails/DM me, etc.

Best case scenario: someone from SFML team picks it up and forks it.
OK scenario: someone who contributed to this project picks it up and forks it (I can also transfer this repo to their account).
Worse-case scenario: there's no one willing to fork it and I'm archiving the repo as-is.

Also see [the previous issue](https://github.com/eliasdaler/imgui-sfml/issues/185) which I posted about this. Since then, no one reached out to help, sadly.

**This repo will be archived on 01.03.2022.**

I've been maintaining this repo for [almost 7 years](https://github.com/eliasdaler/imgui-sfml/commit/c06f73c9d89b633194bc98b310810e2b3e4d4798). I think it's time to move on.
I haven't used SFML for almost [3 years](https://edw.is/porting-to-sdl/) since moving to SDL and have managed to move to Ebitengine since then.

It's hard for me to test changes now since I don't follow SFML's development and don't have much time to follow Dear ImGui's development closely either. 

This project is free and open source software. You're free to fork it and do whatever you want with it (just give proper attribution as specified by MIT license). I want for people to be able to find "the best" fork out of 140 forks which were currently made. That's why I want someone to take control over ImGui-SFML.

I'm glad that this project was useful to many people (I've used it myself for many years). I think I'll make one last release soon (2.6) and currently pending PRs won't be included.

**Comment by eXpl0it3r** [comment]
What about scenario 4 and 5?

- Keep the repository and add some of the past contributors as collaborators
- Transfer the repo to someone who's willing to pick it up

You shouldn't underestimate the visibility of "original source". If I hit a repo that is fork, I always question, whether this is "best" fork I've chosen. It's also why most forks don't work, because people prefer the "original", even if the fork might be more up-to-date and superior in some ways.

**Comment by Rosme** [comment]
I know the SFML team is pretty busy all the time, but would it make sense to have a shared ownership or transfer it to the SFML org?

I do think it is fair that you do not want to work on it and maintain it. And I want to thank you for everything you did.

**Comment by eliasdaler** [comment]
I see, I'm OK with doing this. :)

**Comment by oprypin** [comment]
Hi! Although I'm not putting mich energy into SFML-related projects lately, I'd prefer to be added to this repo so I can keep it alive, rather than having it archived or forked.

I do still maintain https://github.com/oprypin/crystal-imgui-sfml, anyway.

Do consider "scenario 4" - just keep it under your name and add people. The downside is only if you're concerned what people will do to the repo while still having it under your name.

**Comment by eliasdaler** [comment]
@oprypin, thank you. Would you be OK with me transferring this project to you?

> Do consider "scenario 4" - just keep it under your name and add people. The downside is only if you're concerned what people will do to the repo while still having it under your name.

Yeah, I'm somewhat concerned about having low-quality stuff in it and people going to me with demands instead of current maintainers. And if, at some point, I would want to delete my GitHub account, it would be harder to do so with an "active" repo.

**Comment by Bambo-Borris** [comment]
Would love to see it become part of the SFML org personally. It's compact and powerful and has become an essential tool for a lot of SFML users, I think it becoming part of the org should be considered by the SFML maintainers. If not maybe one of them would be willing to take it over.

 I know this is a much loved library for SFML users and the work you did keeping it up to date has been much appreciated. It's power is in how simple it is for a user to grab and get going with ImGui & SFML, something I have benefitted from time & time again. I'm more than willing to contribute again to this in future but I don't think I can take full ownership of it.

**Comment by eXpl0it3r** [comment]
I've created a proposal for the SFML Team to take it up into the org, but it wouldn't become an "official" maintained repository, instead the main contributors will be invited as maintainers.

**Comment by eliasdaler** [comment]
Can I get a link to it, please?

**Comment by eXpl0it3r** [comment]
There's no public link for it 🙂

**Comment by eliasdaler** [comment]
Okay. I'll wait until the decision is done, then.

Also, I'm thinking that making "one last release" wouldn't make sense. Since releases/tags are needed for Conan/vcpkg folks to update their recipes, so it's better if they update the repo link *and* the tag at the same time instead of doing it twice.

**Comment by eliasdaler** [comment]
@eXpl0it3r, any updates?

**Comment by eXpl0it3r** [comment]
We got positive responses, as such, we'd be happy to add it to the organization and add maintainers such as @oprypin. I believe it would give the project additional visibility and we could always transfer it to someone else if the need arises. 🙂

**Comment by eliasdaler** [comment]
That's great to hear!

See this: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization. If organization owners have disabled repository creation by organization members, only organization owners can transfer repositories out of or into the organization.

Looks like you'll need to give me a permission to add repos in SFML organization so that I'm able to transfer this repo.

**Comment by eXpl0it3r** [comment]
You should have a pending invitation 🙂

**Comment by eliasdaler** [comment]
The repo has moved. Thanks a lot, everyone!

I'm not completely abandoning this project. Feel free to request reviews from me if needed. I might also occasionally manage issues and answer the questions people have.

But the project can no go on on its own and I trust SFML team and other contributors to make imgui-sfml even better than it is now. :)

**Comment by oprypin** [comment]
Nice!
Can I be added to the repo? 🙂

**Comment by eXpl0it3r** [comment]
🥳 

@oprypin: You should have received an invite.
