### ISSUE TITLE
Make a new release (2.6)

### ISSUE THREAD

**Issue by eliasdaler** [SFML/imgui-sfml#234]
Nothing major, but a small few fixes were added here and there.

Also need to notify vcpkg and Conan precipice maintainers that the repo address has changed so that they can update it.

**Comment by adrianboyko** [comment]
Would it be a good time to deal with recent deprecations added around Dear ImGui version 1.88? Try:

      #define IMGUI_DISABLE_OBSOLETE_FUNCTIONS
      #define IMGUI_DISABLE_OBSOLETE_KEYIO

**Comment by eliasdaler** [comment]
It's always good time to deal with them. PRs are appreciated. :)

**Comment by adrianboyko** [comment]
I'd help out if it weren't for the fact that I've only just started using ImGui so my experience level is dangerously low :(

**Comment by cosmicr** [comment]
Would also love to see a new release. There have been hundreds of changes and improvements to imgui since version 1.80 - the version imgui-sfml uses. They're now at 1.89.3.

**Comment by eliasdaler** [comment]
@cosmicr FYI, imgui-sfml doesn't depend on a specific version of Dear ImGui. You can use the latest version if you want to.
If you use Conan/vcpkg package, you should ask maintainers to update the dependencies.

**Comment by cosmicr** [comment]
@eliasdaler  Yeah I would do that but my own project is using CMake to fetch imgui-sfml, which in turn fetches the 1.80 version of imgui:
https://github.com/SFML/imgui-sfml/blob/f0d8f72f073b367e9506b8794158cc91f015252e/CMakeLists.txt#L60

I guess I could make a pr for changing this, or there might be another way to get the latest imgui version first, but I'm terrible at writing cmake files lol. 

I'm happy to wait for a new version to reference the latest imgui

**Comment by eliasdaler** [comment]
This only specifies the **minimal** version of Dear ImGui which can be used. 

It doesn't fetch anything - you still need to tell ImGui-SFML where to find Dear ImGui and it will happily use whatever version you provide as long as it's >=1.80.

**Comment by cosmicr** [comment]
Doh you are right, I had forgotten I included a FetchContent_Declare in my cmake to download imgui - I'm already using v1.89 lol. For some reason I thought the imgui-sfml cmake file was magically downloading it. Sorry for wasting your time.

**Comment by eliasdaler** [comment]
No problem :)

**Comment by ChrisThrasher** [comment]
Now is a great time for a 2.6 release now that SFML 2.6 is out.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/imgui-sfml/releases/tag/v2.6
