### ISSUE TITLE
Drawing an sf::VertexArray

### ISSUE THREAD

**Issue by arnokret** [SFML/imgui-sfml#236]
Would you know by any chance a good way to render an sf::VertexArray onto an ImGui window?

**Comment by eliasdaler** [comment]
Hello.
I can recommend drawing it to `sf::RenderTexture` and then drawing it with `ImGui::Image`.

**Comment by arnokret** [comment]
Thanks for the response. I thought of that option, but my Vertex array changes every frame, so then with this method of copying textures around, I would get very low frame rate. 

But, if I understand it correctly, there is no way to somehow directly map the sf::VertexArray to the drawlist in imgui?

**Comment by eliasdaler** [comment]
> I thought of that option, but my Vertex array changes every frame, so then with this method of copying textures around, I would get very low frame rate.

You must be doing something wrong. 

Rendering to a texture shouldn't involve any copying - it's not very different from drawing to a window. 

Maybe you're creating `sf::RenderTexture` in every frame? You shouldn't do that. You should reuse it.

You can also use [ImDrawList](https://github.com/ocornut/imgui/blob/e9743d85ddc0986c6babaa01fd9e641a47b282f3/imgui.h#L2531) directly.
See [this](https://github.com/ocornut/imgui/blob/e9743d85ddc0986c6babaa01fd9e641a47b282f3/imgui_demo.cpp#L7511) example

**Comment by arnokret** [comment]
Thanks a lot for your comment, I was indeed doing something wrong and it is working now. The other pointers you gave are also very helpful.

**Comment by eliasdaler** [comment]
You're welcome :)
