### ISSUE TITLE
SFML_FOUND to FALSE so package "SFML" is considered to be NOT FOUND.

### ISSUE THREAD

**Issue by Mezo-hx** [SFML/imgui-sfml#239]
Just as the Title says, `SFML_FOUND to FALSE so package "SFML" is considered to be NOT FOUND.`

It happens when I was building Imgui-SFML: `cmake <ImGui-SFML repo folder> -DIMGUI_DIR=<ImGui repo folder> -DSFML_DIR=<path with built SFML>`

**Comment by eXpl0it3r** [comment]
And where exactly does SFML_DIR point to?

**Comment by Mezo-hx** [comment]
> And where exactly does SFML_DIR point to?

C:\ExternalLibraries\SFML\lib\cmake\SFML

**Comment by eXpl0it3r** [comment]
Then you probably have different configurations with the current compiler compared to what was used with the compiler to build SFML.

For example 32bits vs 64bits or debug vs release or dynamic vs static

**Comment by Mezo-hx** [comment]
Issue has been fixed, decided to just download it with vcpkg...

but I keep getting this error now when I build it with CMake

```

```

**Comment by eliasdaler** [comment]
@Mezo-hx, please see my [example project](https://github.com/eliasdaler/imgui-sfml-fetchcontent/) on how to use ImGui-SFML with FetchContent.
In particular, you need to set `IMGUI_SFML_FIND_SFML` to `OFF` for everything to work. (you're adding SFML target to your build via `FetchContent_MakeAvailable`, so ImGui-SFML doesn't need to call `find_package(SFML)`)
