### ISSUE TITLE
Update demo code in README

### ISSUE THREAD

**Issue by Lecrapouille** [SFML/imgui-sfml#240]
Hi, in https://github.com/SFML/imgui-sfml/blob/ea890431d2c47e02f84b08d1467a881b88732102/README.md?plain=1#L122

The new way is:
```
    bool show = true;
    ImGui::ShowDemoWindow(&show);
```

**Comment by Trider12** [comment]
There's nothing wrong with the current code. The default argument to this function is `NULL`:
```cpp
IMGUI_API void          ShowDemoWindow(bool* p_open = NULL);
```

**Comment by Lecrapouille** [comment]
@Trider12 ah ok sorry it seemed I was not been able to compile on my side (I'm using the docker branch). I have to check it back
