### ISSUE TITLE
imgui SFML3

### ISSUE THREAD

**Issue by nathanstephane** [SFML/imgui-sfml#257]
With SFML3 not being released, It might be a good idea leaving 2.6 as the main branch. As there are breaking changes with the master branch and SFML 2.6 <=
For example imgui-SFML.h has no declaration for getNativeHandle()

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/imgui-sfml#state-of-development

The intention is to match SFML’s branching strategy. I’m sorry if that disrupts anyone’s workflow but the library has to eventually change the trunk branch to target the new major version of SFML. Imgui-SFML v2 as you know isn’t going anywhere. It simply lives in a new branch now.

**Comment by eliasdaler** [comment]
I think it's worth it setting "2.6.x" as the default branch for this repo because people rarely read README.md and usually expect "master" to be a "stable" branch. (even if it's wrong)

**Comment by nathanstephane** [comment]
> 

Exactly my point :') Thanks @eliasdaler!

**Comment by ChrisThrasher** [comment]
I decided to change the default branch to `2.6.x` so that anyone cloning ImGui-SFML continues to get v2.
