### ISSUE TITLE
imgui-sfml can't find correct version of imgui

### ISSUE THREAD

**Issue by lazzybunny** [SFML/imgui-sfml#288]
I've got the error in cmake 

CMake Error at src/include/imgui-sfml/cmake/FindImGui.cmake:51 (message):
  ImGui at with at least v1.89 was requested, but only v1.82 was found
Call Stack (most recent call first):
  src/include/imgui-sfml/CMakeLists.txt:42 (find_package)

But i've got imgui version 1.91.1 WIP

what might be wrong ?

**Comment by eliasdaler** [comment]
Looks like [this regex](https://github.com/SFML/imgui-sfml/blob/bf9023d1bc6ec422769559a5eff60bd00597354f/cmake/FindImGui.cmake#L50) + CMake's `VERSION_LESS` can't handle "X.Y.Z WIP" version properly.

For now I'd suggest using a non-WIP version, e.g. v1.91.0.

@ChrisThrasher - FindImGui.cmake should probably deal with this "WIP" stuff somehow, also this line in root CMakeLists.txt should probably be only called when `IMGUI_DIR` is not set manually.

```cmake
find_package(ImGui 1.89 REQUIRED)
```

**Comment by lazzybunny** [comment]
Thanks a lot! I changed the version, but it didn't helped) As i understood cmake takes the old files from _deps and recreate them somehow even if i delete everything old, including old builds and cash) So i need somehow to limited cmake to use only files from the source path and not touching else, but it's more cmake questions) Thanks anyway)

**Comment by lazzybunny** [comment]
Solved the problem by changing the _deps cmake build files to the new one by my self, and disconnected "fetch content" in cmake configuration! You could close the discussion, thanks a lot! Have a nice day :)
