### ISSUE TITLE
sf::Cursor::createFromSystem() is not found

### ISSUE THREAD

**Issue by Connnnn9** [SFML/imgui-sfml#309]
I wish there is a video for how to set up ImGui-SFML, anyways, in my project the imgui-sfml.cpp occurs a lot of errors, such as the topics one, and also some like
 textureRect.position.componentWiseDiv(textureSize)),
(textureRect.position + textureRect.size).componentWiseDiv(textureSize)),
textureRect does not have position. and size.

**Comment by ChrisThrasher** [comment]
Your issue lacks much of the context required to help you fix this. If you want this kind of troubleshooting help, please join the [SFML Discord server](https://discord.gg/nr4X7Fh). GitHub is not the right place for these questions.

**Comment by eliasdaler** [comment]
While the context is certainly missing, I don't feel like asking people to join SFML Discord is a right way to help them.

Connnnn9 could have posted their entire error log, compilation setting etc. and we could help them here. 

"GitHub is not the right place for these questions." - is a bit too harsh, imo.
